name: clusterapplication
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  file: ^6.1.2
  platform: ^3.0.2
  http: ^0.13.3
  flutter_spinkit: ^5.2.1
  getwidget: ^4.0.0
  google_fonts: ^4.0.0
  webview_flutter: ^4.9.0
  cupertino_icons: ^1.0.8
  webview_flutter_android: ^3.16.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.12  # Updated to ensure compatibility
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
